### ISSUE TITLE
Firebase Node

### ISSUE THREAD

**Issue by fusion4github** [adrielcafe/gwent-wallpapers#1]
Hello What is the firebase structure for this app. Thanks!

**Comment by adrielcafe** [comment]
Hey,

It only uses Crashlytics and Analytics from Firebase.

The images are located in their own repository: [adrielcafe/gwent-cards](https://github.com/adrielcafe/gwent-cards)

At runtime I create the following URL: https://cdn.jsdelivr.net/gh/adrielcafe/gwent-cards@7.1/cards/front/original/1017.webp

Did I answered your question?

**Comment by fusion4github** [comment]
Hello, I have learnt a lot from your code as I took it for
educational purposes,
Just can I know from where I can add my wallpapers just to test it!
Thanks in advance!

**Comment by adrielcafe** [comment]
To add your own wallpapers: on [WallpaperRepository](https://github.com/adrielcafe/gwent-wallpapers/blob/master/data/src/main/kotlin/cafe/adriel/gwentwallpapers/data/internal/repository/WallpaperRepository.kt) replace the `cardFronts` and `cardBacks` with our list of cards (instead of reading from the bundled storage).

Ex: 
```kotlin
// Current implementation
private val cardFronts by storage.value(KEY_CARDS_FRONT, emptyList<GwentCardFront>())

// Adding our own cards
private val cardFronts = listOf(/* instances of GwentCardFront */)
```

**Comment by fusion4github** [comment]
I know this isn't right place to ask but can you share your telegram/skype ID?
I may disturb you by asking some general question please!
Thanks in advance!
